### ISSUE TITLE
Use SemVer for model versioning

### ISSUE THREAD

**Issue by feynmanliang** [ucbrise/clipper#198]
Model version is current stored as an `int` (see https://github.com/ucbrise/clipper/blob/develop/src/libclipper/include/clipper/datatypes.hpp#L14 and https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_manager.py#L453) which makes it difficult to distinguish whether a version bump is a bug-fix or feature and whether it's is backwards compatible.

[SemVer](http://semver.org) could be adopted for managing model versions to better faciliate this.

**Comment by feynmanliang** [comment]
Relates to #197 #191

**Comment by dcrankshaw** [comment]
#197 should be sufficient to support semantic versioning if the user wants. I don't want to enforce a particular versioning scheme because different uses cases will have different versioning requirements. I'm pretty sure that there are use cases where semantic versioning of models doesn't make sense.
