### ISSUE TITLE
Deploying model from s3 fails for clipper running inside non-Debian distros

### ISSUE THREAD

**Issue by feynmanliang** [ucbrise/clipper#199]
https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_manager.py#L513 requires `dpkg-query`, a tool only available in Debian-based linux distros. As a result, dockerized deployments of clipper require the use of a ubuntu/debian base and lighter-weight container distros (e.g. alpine) cannot be used. This definitely impacts container image size and may also introduce performance overhead due to unneeded OS subsystems.

Instead of using `fabric` to run `aws s3`, we could use [boto](https://boto3.readthedocs.io/en/latest/) to remove this dependence on the OS distro.

**Comment by dcrankshaw** [comment]
That bit of code is legacy that I actually ripped out in #196 until we can support it better. However, note that that code does not actually run inside Clipper docker containers, but is instead used to pull model data to the local file system which a Clipper model container can then read. The right way to address this is to let model containers read model data from non-local paths. This is technically already supported, because model containers can do any IO they want during initialization, but `clipper_admin.Clipper.deploy_model()` will automatically try to copy model data to the node Clipper is running on.

Refactoring how and where model data gets stored will be important as part of the ongoing effort to refactor the clipper admin library and provide better support for cluster management. Ideally, Clipper stores all model data (i.e. all container initialization dependencies) in some sort of blob store that the whole serving cluster can read from. Something like S3 might work, but I don't want to be tied to particular AWS services. Anyway, this is a really good point that warrants further design discussion.

**Comment by dcrankshaw** [comment]
Ahh, and I now see that you identified this point in #200!
