### ISSUE TITLE
Update ReadMe and Documentation

### ISSUE THREAD

**Issue by rlnsanz** [ucbrise/clipper#256]
The `register_application` method of Clipper has been updated to take 5 arguments, but the GitHub ReadMe, and Clipper API documentation only mention 4 arguments.

**Comment by dcrankshaw** [comment]
Ahh good catch. It's actually the other way around: the old version took 5 arguments and we updated it. I did two things to address this:

1. I added a note to the README in #257 to clarify that the quickstart in the readme corresponds to the API version in that commit, not necessarily the released version.
2. I fixed the default documentation branch on readthedocs so that <http://docs.clipper.ai> redirects to the docs for the current release instead of the latest commit.
