### ISSUE TITLE
Enable Clipper to run with multiple query frontend replicas

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#310]
Allowing Clipper to run with multiple query frontend replicas is desirable to provide high availability and to provide horizontal scaling to higher throughputs. There are a few blockers to implementing this currently, the biggest blocker has to with Kubernetes load-balancing ([quoting from the docs](http://clipper.ai/tutorials/container_managers/#known-limitation-query-frontend-scaleout))

>Kubernetes makes it simple to horizontally scale a service by increasing or decreasing the number of replicas of a pod. Clipper uses precisely this mechanism to scale the number of replicas of a model container. However, scaling the query frontend service to multiple replicas (e.g. to make it highly available), is significantly more complicated. The complication arises primarily from the fact that model containers connect to the query frontend with long-lived RPC connections (over TCP). These connections last until either the query frontend or the model container dies and kills the connection. As a result, these long-lived connections must be correctly re-balanced when query frontend replicas are created or destroyed. Without a re-balancing mechanism, the query frontend and model container deployments cannot scale independently.
> 
>Clipper does not currently provide any support for this re-balancing. The query frontend is stateless, and so there is no architectural reason why it cannot be replicated, but you will need to manage this re-balancing yourself. We are currently investigating the best way to support this use case.

This issue is meant to be a blanket issue to track the current state of the feature. Individual issues to add the functionality needed to enable query frontend scaleout will be filed as they come up.

**Comment by santi81** [comment]
@dcrankshaw In addition to the issue mentioned above , the Query Frontend is pseudo-stateless because of the cache.I guess it would be hard to scale out with this kind of approach.Do you think moving to Redis as a distributed cache would be an option?

**Comment by dcrankshaw** [comment]
Yeah we would consider this. I think that long-term, it makes sense to move the cache outside of Clipper entirely. You don't want the cache in front of Clipper because it needs to be aware of model versions, but it makes sense to have a single shared cache among all query frontends rather than rolling our own. @santi81, can you file an issue requesting this feature?

**Comment by withsmilo** [comment]
@dcrankshaw 
I met this issue. When I increased the replicas of query-frontend from 1 to 2, Clipper gave me so slow replies about some requests.

**Comment by dcrankshaw** [comment]
Yeah I'm not surprised. Clipper doesn't support multiple query frontends in the same cluster currently, so I'm not surprised that this broke things. We're working on this right now.

**Comment by withsmilo** [comment]
Great! Our team is using Clipper to deploy our model in a closed environment, and trying to widen the target customers. In the point of view to scale-out the system, this issue is a big obstacle.

**Comment by dcrankshaw** [comment]
Cool! Yeah we know this is one of the big blocking obstacles to using
Clipper in more production environments. We will update this issue with
progress soon.

**Comment by withsmilo** [comment]
@dcrankshaw : Please let me share your works. What is your plan to change QueryFrontend's architecture?

**Comment by dcrankshaw** [comment]
I'm currently working on a design doc for this. I will post it to this
issue as soon as it's ready for comments. Should be by the end of the week.

**Comment by Jeffwan** [comment]
By the way, Is current RPC implementation a problem to scale out query frontends? Now model container plays a role like rpc client (DEALER/REQ) and query frontend is like Server(ROUTER/REP). If we have more replicate query frontend instances,

- Model containerA connects to one of query frontend instance B through kubernetes Load balancing. There would be a problem if traffic are load balanced on other query frontend instance A, it may not have long connection to containerA and cannot serve predictions.

I think model containers can play role of ROUTER and query frontend as DEALER. Every query frontend instance can keep mapping like <modelMeta, List<ContainerID>>,  <modelMeda, currentConnection>

Consider scale up/down cases,

- query frontend scale up , it knows target model containers and build mapping from db. If there's traffic coming through this server, it select one live container and setup session. 
- query frontend scale down, long-lived RPC (client side) are closed. no effect. 
- model container scale up,  query frontend side will detect (rSubscriber) this change, it will be registered in in-memory mapping table. -> map.get(modelMedta).add(instance.id)
- model container scale down,  RPC server side closed. RPC client timeout, close socket and update mapping tables to avoid future traffic go to died container. 

The problem is initial session setup from query frontend to any new model container will take longer since it doesn't have long-lived connection. Once it has one, serving latency will be lower.

**Comment by withsmilo** [comment]
Any update here?

**Comment by dcrankshaw** [comment]
This is in progress. @rbala19 can you give a brief summary of what we tried and what you're working on now?

**Comment by rbala19** [comment]
Over the past two weeks, we've been looking into a more fault tolerant implementation of the query-frontend to model interaction. Currently, we have a system in place that allows the user to specify how many query-frontend replicas they want to deploy. Once these replicas are deployed, any model that is subsequently deployed will be deployed to each replica frontend. 

In addition to increasing fault tolerance through model replication, we aim to increase resilience in the event of a query frontend crash. Kubernetes restarts crashed containers automatically when using a ReplicaSet deployment; however, deployments often restart with differing IPs, implying that the restarted query frontend will lose its connection its models. Unfortunately, there is no method of preventing a crashed query frontend from automatically restarting, since Kubernetes forcibly asserts a certain number of pods to be running within the ReplicaSet deployment type. To remedy this, we have several tasks in progress: 

- Place a listener that periodically checks for a crashed frontend; collect the IP of the newly deployed query-frontend. 
- Replicate all deployed models from one of the deployed query frontends into the restarted query frontend.
- Place this functionality within a pod of its own that deploys whenever clipper deploys. This pod will function as an overseer to which we will deploy future changes to fault tolerance and replica scaling.

**Comment by withsmilo** [comment]
@dcrankshaw 
Is it true?
> Currently, we have a system in place that allows the user to specify how many query-frontend replicas they want to deploy. Once these replicas are deployed, any model that is subsequently deployed will be deployed to each replica frontend.

**Comment by Jeffwan** [comment]
@rbala19 @dcrankshaw 
Instead of making changes on existing solution, I am thinking is it possible to ask query processor to connect to model containers ? (models can be deployed as kubernetes service)
1. Everytime end user deploys a model, write <model, k8s-service-lb> in meta store.
2. For every prediction request, query processor get model endpoint from meta store.
3. Query processor send rpc request to model container service

In this case, I know it will hurt performance a little bit. (without benchmark, I don't know how much). But from scalability and maintenance perspective, architecture looks  easier. Have your team considered this way? If so, please let me know the reason you didn't move on. 
1. no need to keep long-alive connection. 
2. no heartbeat. K8s will guarantee replicas always alive.

**Comment by dcrankshaw** [comment]
You're right that it simplifies the architecture. However, that approach has two big drawbacks.

1) Initiating a new connection for each request adds a significant amount of overhead, and will substantially impact our ability to meet latency SLOs.
2) The query frontend has a single request queue that dispatches to all replicas of a model. We carefully load-balance and dispatch these requests in batches to replicas as they become available for work. In particular, when a given replica finishes processing a batch, it requests more work from the queue, rather than having Clipper push a batch to it (when it might not be ready). Furthermore, while we haven't added this yet, we are designing a more sophisticated batching algorithm that will automatically learn the latency characteristics of each model container individually and tailor the batch size to be used based on the container the batch will be sent to. Taking the approach you describe would make this feature very hard (if not impossible) to implement.

**Comment by withsmilo** [comment]
@dcrankshaw 
For container orchestration I use Docker Swarm, not Kubernetes. In this case, if I increase the replicas of Query-Frontend, Clipper gave me so slow replies about some requests. Through inspecting Clipper codes, I found that _current Clipper architecture does not support Docker Swarm_, in which multiple replicas of a Swarm service have **the same IP and port**. So I modified Clipper architecture like this,

1. [model container - rpc.py - RPCService]
Retrieve the own hostname(hn_M).
2. [model container - rpc.py - send_container_metadata()]
Send hn_M with other information to Query-Frontend.
3. [query-frontend - rpc_service.cpp - RPCService::receive_message()]
Receive hn_M and other information from upper model container.
4. [query-frontend - rpc_service.cpp - RPCService::receive_message()]
Retrive the own hostname(hn_Q) and **set hn_M as model_replica_id and hn_Q as qf_replica_id.**
5. [query-frontend - rpc_service.cpp - RPCService::receive_message()]
Add hn_M and hn_Q with other information to Redis by calling redis::add_container().
```
<
  (model_name, model_version, model_replica_id, qf_replica_id),
  model_id, model_name, model_version, model_replica_id, qf_replica_id, zmq_connection_id, batch_size, input_type
>
```
6. [query-frontend - task_executor.hpp - callback of subscribe_to_container_changes()]
    1. Extract a qf_replica_id(hn_Q) from the changed container information.
    2. Retrive the own hostname
    3. Ignore the callback if hn_Q is different from the own hostname.

Currently, our modified Clipper having multiple query-frontend replicas is working well. :)

**Comment by dcrankshaw** [comment]
@withsmilo Oh very cool. Glad to hear you got this working for your use case. And thanks for sharing here! This should help future users who have similar use cases to yours.

**Comment by dcrankshaw** [comment]
Added in #462

**Comment by yangzz945** [comment]
> @dcrankshaw
> For container orchestration I use Docker Swarm, not Kubernetes. In this case, if I increase the replicas of Query-Frontend, Clipper gave me so slow replies about some requests. Through inspecting Clipper codes, I found that _current Clipper architecture does not support Docker Swarm_, in which multiple replicas of a Swarm service have **the same IP and port**. So I modified Clipper architecture like this,
> 
> 1. [model container - rpc.py - RPCService]
>    Retrieve the own hostname(hn_M).
> 2. [model container - rpc.py - send_container_metadata()]
>    Send hn_M with other information to Query-Frontend.
> 3. [query-frontend - rpc_service.cpp - RPCService::receive_message()]
>    Receive hn_M and other information from upper model container.
> 4. [query-frontend - rpc_service.cpp - RPCService::receive_message()]
>    Retrive the own hostname(hn_Q) and **set hn_M as model_replica_id and hn_Q as qf_replica_id.**
> 5. [query-frontend - rpc_service.cpp - RPCService::receive_message()]
>    Add hn_M and hn_Q with other information to Redis by calling redis::add_container().
> 
> ```
> <
>   (model_name, model_version, model_replica_id, qf_replica_id),
>   model_id, model_name, model_version, model_replica_id, qf_replica_id, zmq_connection_id, batch_size, input_type
> >
> ```
> 
> 1. [query-frontend - task_executor.hpp - callback of subscribe_to_container_changes()]
>    
>    1. Extract a qf_replica_id(hn_Q) from the changed container information.
>    2. Retrive the own hostname
>    3. Ignore the callback if hn_Q is different from the own hostname.
> 
> Currently, our modified Clipper having multiple query-frontend replicas is working well. :)

Your method is very good. I have the same problem and resolve it throug your method。Thanks
