### ISSUE TITLE
query frontend error when running concurrent requests

### ISSUE THREAD

**Issue by bdod6** [ucbrise/clipper#312]
I'm testing clipper by running two python scripts concurrently that queries the front-end for a prediction. Here's the  script

```
df = pd.read_csv('test_predictions.csv', sep=',',header=0, index_col=0)
df_inputs = df.values

headers = {"Content-type": "application/json"}
for row in df_inputs:
    row_list = list(row)

    prediction = requests.post("http://localhost:1337/xg-app/predict", headers=headers,
                               data=json.dumps({"input": row_list})).json()

    print(prediction)
```

This runs fine when I run it normally. However, running concurrently causes the model to crash. The model throws a `ValueError: feature_names mismatch:`. I think this error is occuring because the model will occasionally receive an input list that is twice as long as what it's expecting, so it looks like the query frontend is sending concurrent requests as a single request to the model?

Using a model that accepts any length X does not result in an error. 

Also, adding replicas does not solve this problem. The replicas will run, and start going down one by one when it receives the double-length input.

**Comment by dcrankshaw** [comment]
I suspect this is caused by Clipper's use of batching. To improve throughput, Clipper will send a batch of predictions at a time to the model. [This section](http://clipper.ai/tutorials/basic_concepts/#defining-a-model) of the user guide should help you fix your model, but the TL;DR is that models **should take a list of inputs as argument and return a list of strings.**

**Comment by bdod6** [comment]
thanks for the fast response. 

I believe I am taking in a list of inputs for my model though? I'm using a pickled XGBoost model for the prediction, but this is the python function:

```
def xg_predict(x):

    X = np.array(x).reshape(1,-1)
    X_row = scipy.sparse.csc_matrix(X)

    y_pred = model.predict(X_row)
    return [str(y_pred)]
```

So are you basically saying there's no way prevent Clipper from sending batch requests to the model? This seems like a major limitation since instead of a single output per request, the model will randomly need to parse and output multiple predictions when it receives a batch from Clipper.

**Comment by dcrankshaw** [comment]
You shouldn't need to do any parsing or anything. The predict function is called with a Python list of numpy arrays, where each element in the list (i.e. each numpy array) is the input from a single request.

If you want your model to process a single input at a time, just wrap the model call in a for-loop. Try the following modification to the above function:

```py
def xg_predict(xs):
    preds = []
    for x in xs:
        # Note I removed the call to np.array here since x is already a numpy array
        X = x.reshape(1,-1)
        X_row = scipy.sparse.csc_matrix(X)

        y_pred = model.predict(X_row)
        preds.append(str(y_pred))
    return preds
```

**Comment by dcrankshaw** [comment]
You're right that this is a little bit confusing for new users though. We won't be removing batching because it's pretty critical for performance for some models, but we plan on making batching optional in #285 so model containers are easier to write.

**Comment by withsmilo** [comment]
How about below code?
```python
def xg_predict(xs):
    def _predict(x):
        X = x.reshape(1,-1)
        X_row = scipy.sparse.csc_matrix(X)
        y_pred = model.predict(X_row)
        return [str(y_pred)]
    return map(_predict, xs)
```

**Comment by dcrankshaw** [comment]
@withsmilo That would work too, but in that case `_predict` should just return `str(y_pred)`, not `[str(y_pred)]`

**Comment by bdod6** [comment]
Sorry, i didn't mean to say that doing the for loop was the actual problem. It's more that the model will randomly output two predictions in a list when clipper decides to batch requests. So in a real-time prediction scenario, we are sending a request to Clipper, and the service expects a single prediction back so it can take the right action. The throughput is several hundred requests per second, so Clipper would need to be able to handle concurrent requests without batching. 

I guess the only option is to wait for the update in #285 ?

**Comment by dcrankshaw** [comment]
I'm not sure I understand the problem. To be explicit, batching works in the following way. Imagine I have two clients, Alice and Bob.

If only Alice sends a request, Clipper will forward that single query in a batch of size 1 to the model. The model will make a prediction on that query and return a list of predictions with 1 element to Clipper. Clipper will take that prediction and return the result to Alice.

Now imagine Alice submits a request then immediately afterward Bob submits a request to the same model. Both of those requests will end up in the same queue, with Alice's request ahead of Bob's. Clipper will group those two requests into a single batch of size two. Alice's request will be the first element in the batch and Bob's will be second. Clipper will send that batch to the model, which will make two predictions and return a list of two predictions. When Clipper receives the response from this model, it will extract the individual predictions from the batch. It knows the order of requests in the batch, so it knows the first prediction in the response belongs to Alice, and the second to Bob. It then returns these predictions as responses to the appropriate clients. So even though Alice and Bob's requests were batched together, Alice only gets her response and Bob only gets his response. The response to the client should not be affected by what other requests (if any) were in the batch.

Is this not the behavior you are observing?

**Comment by bdod6** [comment]
ahh...thanks for the explanation! I hadn't realized that Clipper would unbatch and correctly route the requests. I had just assumed the request would receive the final output in model function. Tested it and now works as expected. That makes sense now... thanks!

**Comment by santi81** [comment]
@dcrankshaw I tried to test this behavior but haven't been successful in seeing batching work.From the logs of the model server it can be seen that the model server is actually receiving 2 request instead of one.

**Comment by dcrankshaw** [comment]
@santi81 I'm not sure what you mean. In general batching should be transparent to the clients. What type of behavior were you expecting to observe?

**Comment by santi81** [comment]
@dcrankshaw sorry i wasn't clear.This is what i tried.Deployed a simple python model in which the predict function exactly returns the size of input list to test batching.Something like:

` def feature_batch(xs):
     print("Query incoming")
     return [str(len(xs)) for x in xs]`

Linked this model to an application with slo of 10 seconds. Then sent 2 requests almost at the same time.I was expecting that the model predicts a value of 2 but instead was predicting 1 .

I checked the docker logs of the model container .It showed "Query Incoming" twice.
My expectation was that the query_frontend received 2 queries batches them and passes them a list of numpy arrays to the models predict function.

Is there any unit test or integration test for this, so that i can look if i was doing something wrong.

**Comment by santi81** [comment]
@dcrankshaw can you please let me know if my understanding from above is correct?

**Comment by dcrankshaw** [comment]
There isn't a test for this specifically. But if your model container showed that it received two queries, then it didn't batch them. The following function is probably the easiest way to observe batching.

Deploy the following function using the Python model deployer:

```py
import time
def demo_batching_func(inputs):
    print("Got batch of size {}".format(len(inputs)))
    time.sleep(1)
    return [str(len(inputs)) for _ in inputs]
```

Once you've deployed that function, send multiple requests to Clipper simultaneously. They don't have to be sent at exactly the same time (just close), but you need multiple in-flight queries at once. So for example, sending the queries from a Python for loop with blocking (synchronous) HTTP requests won't work because the second query wouldn't be sent until the first one completes, so they cannot be in the same batch.

Also, you probably need to send more than 2 queries to observe batching. I would try sending at least 10. The very first query will be executed in a batch by itself because there is very little time for the queue that batches are pulled from to build up.
