### ISSUE TITLE
Re-link an app to other model

### ISSUE THREAD

**Issue by withsmilo** [ucbrise/clipper#345]
After registering my app and model A to Clipper, can I re-link my app to other model B? 
If I cannot, why do you limit apps to having at most 1 linked model?

**Comment by Jeffwan** [comment]
def link_model_to_app(self, app_name, model_name) is used to re-link your app to other models.

**Comment by withsmilo** [comment]
@Jeffwan : 
It can't. Sources said, if the application has previously been linked to a different model, link_model_to_app() will fail. ([codes](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/clipper_admin.py#L205-L207))

**Comment by Corey-Zumar** [comment]
@withsmilo I will review #254 which should allow you to re-link your application to a different model. Currently, we only support linking to one model at a time because multi-model queries require a protocol for combining model outputs to generate a single response. This functionality will be implemented in a future release, ideally supporting UDFs for output aggregation.
