### ISSUE TITLE
Integration tests flaky with "Error starting userland proxy... bind: address already in use"

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper#352]
It seems `clipper_admin_tests.py` causes a lot of unexpected failure. It fails on the same error but with different unit tests that has nothing to do with the code I changed:
- test_inspect_instance_returns_json_dict: Bind for 0.0.0.0:37967 failed: port is already allocated. [829 log](https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/829/console).
- test_python_closure_deploys_successfully: Error starting userland proxy: listen tcp 0.0.0.0:38198: bind: address already in use. [828 log](https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/828/console).
- test_link_not_registered_model_to_app_fails : Error starting userland proxy: listen tcp 0.0.0.0:39526: bind: address already in use. [822 log (for batch predict)](https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/822/console).

**Comment by lgendrot** [comment]
Total shot in the dark here, because I only recently stumbled on Clipper, but I run into port issues like this very frequently in Docker, usually after starting and stopping containers in quick succession. I can usually trace it back to containers I explicitly stopped failing to actually be stopped, or appearing to be stopped (via `docker ps`) but not giving up their ports for one reason or another.

A little digging and I found a lot of examples of similar issues:

https://github.com/moby/moby/issues/25981
https://github.com/moby/moby/issues/34097
https://github.com/moby/moby/issues/7856 

They either claim that whatever the issue was, it was fixed in more recent versions of docker, or the issues are as of yet unresolved. In general the problem seems to be with docker itself, though.

From what I can see the unit tests all run in a container built from `ClipperTestsDockerfile`, and the logs provided show that step of the build process uses the cache, and that line of the Dockerfile hasn't been updated in a while, so maybe building that image with the `--no-cache` flag so it will definitely get the latest version of docker (and everything else) will mitigate this?

Again, shot in the dark.
