### ISSUE TITLE
Issue in deploying models when clipper_admin package is hosted in docker application

### ISSUE THREAD

**Issue by hitesh-tarani** [ucbrise/clipper#422]
I am trying to deploy clipper models from an application running in docker on the same host where clipper query & management frontend and redis are running.
I am starting my clipper connection with container manager:
DockerContainerManager(docker_ip_address=`<my-ipv4-addr>`)

But the deployment is failing with the following traceback:
`Traceback:`
```
  File "/usr/local/lib/python2.7/dist-packages/clipper_admin/deployers/python.py", line 188, in deploy_python_closure
    registry, num_replicas, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/clipper_admin/clipper_admin.py", line 298, in build_and_deploy_model
    container_registry)
  File "/usr/local/lib/python2.7/dist-packages/clipper_admin/clipper_admin.py", line 393, in build_model
    fileobj=context_file, custom_context=True, tag=image)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/images.py", line 181, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 247, in build
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 188, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```
In the docs [http://docs.clipper.ai/en/release-0.2/#clipper_admin.DockerContainerManager](url),
it's mentioned that `docker_ip_address` should almost always be "localhost". 
Does clipper support deployment from within docker application?
If not, what's the alternative for this

**Comment by withsmilo** [comment]
@hitesh-tarani 
You have an error failed to build your Docker image. I think that your error has nothing to do with `docker_ip_address` .

**Comment by hitesh-tarani** [comment]
This was an issue with running docker-py inside docker container.
Needed to bind-mount docker socket in the container.
Reference: [https://github.com/docker/docker-py/issues/1334](https://github.com/docker/docker-py/issues/1334)

Thanks, for the help. Closing the issue.

**Comment by csmithnm** [comment]
Can someone please give me a hint how I would "bind-mount docker socket in the container" for the clipper_admin?  
I am trying the Clipper.ai "Getting Started" and I have tried digging into the clipper_admin code, but I am having issues finding the exact location of where to add the mount: 
`-v /var/run/docker.sock:/var/run/docker.sock`
Would that be in the clipper/clipper_admin/docs/Makefile ?  Under the `SPHINXOPTS` option?
I am really interested to try out this framework since I built my own deployment environment just for R. I would prefer having something more open and easier to setup. Any hints would be greatly appreciated.

**Comment by csmithnm** [comment]
CORRECTION: After more digging...I see that clipper/clipper_admin/docs/Makefile is completely wrong because it is for documentation.  I am now digging into the DockerContainerManager() API possibly under the `extra_container_kwargs={}` option.

**Comment by csmithnm** [comment]
SOLVED:  After more digging, I found the issue was with NOT having Docker running (sorry, total noob error). So I started up Docker and then ran into a "Permission denied" error.  Which probably has to do with having installed Anaconda2 via root. So I sudo'd  to root: `sudo su -`, then started `ipython` and issued the [Clipper.ai Getting Started](http://clipper.ai/) commands and got Clipper running.
