### ISSUE TITLE
Enable multiple Clipper clusters to be running concurrently in Docker & Kubernetes

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#460]
We should allow users to specify a cluster name for Clipper when starting an instance. Then a ClipperConnection object should be associated with that specific cluster name. This will enable multiple clusters to be running side by side on the same K8s cluster, which is useful for supporting multi-tenancy applications and will help with testing.

This can be achieved via a slight modification of the way we use Kubernetes labels to identify Clipper instances.

**Comment by dcrankshaw** [comment]
Alternatively we can use Kubernetes namespaces to achieve this

**Comment by simon-mo** [comment]
As a note: this will also fix #424 #448 ~#501~

**Comment by simon-mo** [comment]
Implementation Note:

## Docker
Docker multi-tenancy will be implemented via adding labels to containers. In Docker, each `run` command will always create a new container. Each container will have a randomly generated name which is used as unique identifier.

## Kubernetes
We can't do the same in k8s because k8s use `name` as unique identifier. However, the `name` is specified by users. Therefore, we must:
- When creating new deployment/services, we generate name as `cluster_name`+`name`
- We also want to add labels for:
   - cluster
   - function {mgmt, query, etc..}

**Comment by simon-mo** [comment]
Closed by #503
