### ISSUE TITLE
how to serve pretrained pytorch/tensorflow/scikit models

### ISSUE THREAD

**Issue by sujit420** [ucbrise/clipper#466]
I am using deploy_pytorch_model() method, passing my pytorch model as a parameter. It gets stuck every time after saying: "Found 0 replicas of <model name>: adding 1"
Simultaneously, I am getting error while deploying : "Error saving torch model: Translate instance has no attribute 'state_dict'"
Note: I am using a pre-trained pytorch model of type dict.

**Comment by simon-mo** [comment]
@sujit420 

1. `deploy_pytorch_model()` needs prediction function that takes (model, input) as parameter as well. 
2. The model needs to be pytorch model instead of a dict. You might need to use `model.load_state_dict` to load the parameter into a pytorch model (`nn.Module`) object .

See more at: http://pytorch.org/docs/master/notes/serialization.html

**Comment by rkooo567** [comment]
Resolved
