### ISSUE TITLE
XGBoost Deployment Example is not working

### ISSUE THREAD

**Issue by vijinkp** [ucbrise/clipper#513]
I am getting following error in docker logs while running XGBoost deployment example in Ubuntu 18.04 box.
Got start of message 0 
Traceback (most recent call last):
  File "/container/python_closure_container.py", line 61, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 167, in handle_prediction_request
    (len(prediction_request.inputs), len(outputs)))
rpc.PredictionError: 'Expected model to return 2 outputs, found 1 outputs'
Encountered error not related to missing packages. Please refer to the container log to diagnose.

Please help me out why its happening?

**Comment by simon-mo** [comment]
Thanks for submitting this issue! @RehanSD Can you take a look?

**Comment by RehanSD** [comment]
Hi vijinkp! Thanks for pointing this out. Its actually an error in the tutorial itself, so we'll fix it soon. Keep an eye on this thread for when the updated version is out.

**Comment by RehanSD** [comment]
Hi @vijinkp! The Clipper system recently adopted adaptive batching, that this tutorial did not account for. We are making changes to the tutorial to account for this feature, and you should see no error.

1. Adaptive Batching - When the server is under load we add duplicates of the requests to measure how long this model takes given some batch size, to find out the optimal batch size for the model container.
2. Fix: Change your predict function to this:
```py
def predict(xs):
     return [str(bst.predict(xgb.DMatrix(x))) for x in xs]
```
This should make it so that every element in the batch is processed!

**Comment by vijinkp** [comment]
Thanks @simon-mo @RehanSD . 
I tried the code snippet provided and data structure used for query input was list<list<int>>. I am getting following error.
{'error': 'Json error', 'cause': 'Error parsing JSON: Array input of type Array is not of type float. Expected JSON schema: \n  {\n   "input" := [double] | [int] | [string] | [byte] | [float],\n  }\n'}

How does predict function and query request will look like if prediction input is of batch size = 1 and single prediction input has a feature size more than 1?

It would be of great help if you could provide a template for predict function and query request.
Thanks in advance.

**Comment by vijinkp** [comment]
I was able to run the example if i specify batch_size=1 in 'deploy_python_closure' function.

**Comment by RehanSD** [comment]
Hi @vijinkp! It seems like you’ve made some progress overnight, but to answer your original question, specifying a batch size of 1 and sending an array of inputs is perfectly acceptable. I think you may have gotten the error you mentioned because you returned an array of arrays and not an array of floats. If you could specify where you got the error (whether when sending requests or when returning results) that would be great, and allow me to try and replicate and figure it out!

**Comment by vijinkp** [comment]
@RehanSD Since i was trying to test the model with batch_size of more than 1, i was passing an array of arrays to predict function. That resulted in following error.
{'error': 'Json error', 'cause': 'Error parsing JSON: Array input of type Array is not of type float. Expected JSON schema: \n {\n "input" := [double] | [int] | [string] | [byte] | [float],\n }\n'}

**Comment by RehanSD** [comment]
Hi @vijinkp! To get a batch size greater than 1, after specifying the desired size in the deploy function call, you just need to send multiple queries normally, and Clipper will batch them for you. For example, if you wanted a batch size of two, with the inputs `[1, 2, 3]` and `[4, 5, 6]`, instead of sending 1 query with the input being `[[1, 2, 3], [4, 5, 6]]`, you would send one query with the input `[1, 2, 3]` and a second query with the input `[4, 5, 6]`, and Clipper would handle the batching for you. This would also alleviate the error you mentioned since you are now sending data that is appropriately formatted.

**Comment by vijinkp** [comment]
Hi @RehanSD Will Adaptive batching work even if we mention batch_size=1 in each query? One more query, Do you have any end to end example of pytorch/tensorflow model deployment and querying?

**Comment by RehanSD** [comment]
AHi @vijinkp! I actually made a mistake in my previous answer. If you would like to send a batch of some size, send the array of arrays as you tried, but change the attribute in the query from `input` to `input_batch`. For more info on adaptive batching, check out these [docs](http://docs.clipper.ai/en/v0.3.0/_modules/clipper_admin/deployers/python.html?highlight=batch_size), but the short answer is that specifying batch size disables adaptive batching. For examples on pytorch/tensorflow model serving, check out our [integration tests](https://github.com/ucbrise/clipper/tree/develop/integration-tests) especially those for [pytorch](https://github.com/ucbrise/clipper/blob/develop/integration-tests/deploy_pytorch_models.py) and [tensorflow](https://github.com/ucbrise/clipper/blob/develop/integration-tests/deploy_tensorflow_models.py) which I think should work for your needs.

**Comment by vijinkp** [comment]
@RehanSD Thanks a lot.. It worked for me.

**Comment by RehanSD** [comment]
I'm glad @vijinkp!
