### ISSUE TITLE
Monitoring is not working on  google cloud

### ISSUE THREAD

**Issue by YogeshSomawar** [ucbrise/clipper#564]
I have deployed the clipper on google cloud successfully. Also able to deploy the models successfully.
But not able to any monitoring data in Prometheus.

Getting the following error in metrics POD in the google cloud

`level=error ts=2018-08-30T06:24:25.375947359Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:296: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods at the cluster scope: Unknown user \"system:serviceaccount:default:default\""`

Looks like some permission issue.

Could somebody help me with this?

**Comment by simon-mo** [comment]
Hi @YogeshSomawar I'm aware of this. All we need is to add RBAC support in our kubernetes config files. (See https://github.com/prometheus/prometheus/blob/master/documentation/examples/rbac-setup.yml)

Unfortunately we don't have the bandwith to work on this issue until next month. If you can help contribute that would be great; otherwise we will try fix this soon.

**Comment by YogeshSomawar** [comment]
Thanks for the updates.
I will try by adding RBAC support in our kubernetes config.

**Comment by jacekwachowiak** [comment]
Hi @YogeshSomawar, I am dealing with the same error, but on Kubespray-based Kubernetes on Openstack. I used your PR to check and there was no difference for me - the error persists.  Have you by any chance tried some other solution or launching Clipper on another cluster? Any info would help!

**Comment by rkooo567** [comment]
Will be handled by this PR. https://github.com/ucbrise/clipper/pull/694

**Comment by withsmilo** [comment]
resolved by #694.
