### ISSUE TITLE
Batching Question

### ISSUE THREAD

**Issue by DNCoelho** [ucbrise/clipper#596]
Does the batching mechanism apply to prediction requests that are themselves made for a batch?
Say I send three requests x, y and z which contain 1, 1, and 2 entries respectively.
If the mechanism tried to batch this requests entries would it form a 4 entry batch or would it only form a 2 entry batch from the entries of x and y while the batch sent through z would be ignored and predicted separately?

My thanks in advance.

**Comment by withsmilo** [comment]
## If you set '-1' as batch size when calling a deployer function like 'python_deployer.deploy_python_closure()',
the adaptive batching policy of Clipper will select a proper batch size automatically. The policy has three batch size determination methods as like,

https://github.com/ucbrise/clipper/blob/3c5a1cc6ce59e0ccd778f526a50808d0e7b2576f/src/libclipper/include/clipper/containers.hpp#L25-L29

But this part is not clear because I have always used predefined batch size. Current policy has a bug (https://github.com/ucbrise/clipper/issues/518)) also.

## If you set '3' as batch size when calling a deployer function like 'python_deployer.deploy_python_closure()',
this value means 'maximum batch size' actually. A working thread which has the responsibility to send 'one batched-request' to the related model container will get it by the following codes. (in other words, all the requests in ModelQueue, but less than the maximum batch size)

https://github.com/ucbrise/clipper/blob/3c5a1cc6ce59e0ccd778f526a50808d0e7b2576f/src/libclipper/include/clipper/task_executor.hpp#L156-L158

So if your three requests are stored in ModelQueue when determining the batch size, all three requests will be handled as 'one batched-request' and be sent to a model container together. And then the model container will receive it as a list of input(ex. [x, y, z]).

**Comment by DNCoelho** [comment]
Thank you for your detailed response!

Regarding that bug in the currentpolicy, can it be avoided by indicating the  batch_size manually in the deployer function? 
As stated in the documentation:
batch_size (int, optional) – The user-defined query batch size for the model. Replicas of the model will attempt to process at most batch_size queries simultaneously. They may process smaller batches if batch_size queries are not immediately available. If the default value of -1 is used, Clipper will adaptively calculate the batch size for individual replicas of this model.

**Comment by withsmilo** [comment]
No. If you would like to avoid the bug, you must apply my workaround patch included in #518 to turn off the adaptive batch policy. With my patch, batch size(-1) will be handled as the same with 1.

**Comment by DNCoelho** [comment]
Ok, once again thank you for the help!
