### ISSUE TITLE
Google Kubernetes: No external node address found

### ISSUE THREAD

**Issue by avinregmi** [ucbrise/clipper#614]
Hello,
I'm trying to setup Clipper on GKE. I've downloaded config.yaml file and credentials.json and from GKE and have initialized in my local computer. 
I'm able to execute and connect to GKE cluster as shown below
![image](https://user-images.githubusercontent.com/32203792/51505648-cb621680-1db5-11e9-8477-466f83e1006d.png)
After running clipper_conn.start_clipper(), I'm getting an error saying: No external node address found. 
![image](https://user-images.githubusercontent.com/32203792/51505682-0d8b5800-1db6-11e9-8885-a3b9602f6c05.png)

I can see that initial clipper pods are deployed in GKE.
![image](https://user-images.githubusercontent.com/32203792/51505695-2ac02680-1db6-11e9-9c09-76bbaf99f869.png)

**Comment by rkooo567** [comment]
Could you try setting useInternalIp=True and run again?

**Comment by avinregmi** [comment]
Yes, turns out it is looking for DNS server in my cluster. Using useInternalIp=True solved the issue. After solving this, I was able to upload models to my cluster but I was unable to communicate with clipper management via REST. I solved it by settingkubernetes_addr_proxy=None and changing kubernetesContainerMananger: get_admin_addr() function. For some reason, this function will return some long url with /api/namespace.... which is not correct for google k8s setting. It should be externalIP of loadbalancer:80. After rewriting that, it worked. Also what is the purpose of kubernetes_proxy_addr field? Is that relevant if I'm using google Kubernetes cluster?

**Comment by rkooo567** [comment]
Based on the API doc, http://docs.clipper.ai/en/v0.3.0/container_managers.html

kubernetes_proxy_addr (str, optional) – The proxy address if you are proxying connections locally using kubectl proxy. If this argument is provided, Clipper will construct the appropriate proxy URLs for accessing Clipper’s Kubernetes services, rather than using the API server addres provided in your kube config. 

It seems to me that when you have a kube proxy to call a kubernetes API server, (like when you use minikube), you need to specify the address though I am not 100% sure. I think for more details, @simon-mo can answer better.

**Comment by withsmilo** [comment]
@avinregmi @rkooo567 
I think this problem depends on the configuration of the k8s.
