### ISSUE TITLE
Apply preprocessing at the prediction time

### ISSUE THREAD

**Issue by tosolveit** [ucbrise/clipper#617]
Hi,
Requests to prediction services usually needs to be processed before triggering prediction function

- Splitting a text in the request and creating multiple features
- Ignore some features like constants
- map a category to an index value
- Standardize based on a predefined range

How can I achieve that, basically instead of using a request like this,
`curl -X POST --header "Content-Type:application/json" -d '{"input": [1.1, 2.2, 3.3]}' 127.0.0.1:1337/hello-world/predict
`

I want to send a request like this,
`curl -X POST --header "Content-Type:application/json" -d '{"input": ["country":"US","income":122]}' 127.0.0.1:1337/hello-world/predict
`

**Comment by withsmilo** [comment]
Clipper permits only "integers", "floats", "doubles", "bytes", or "strings" as input type. So if you would like to pass a data like json format as input type, you must handle it as "strings" type. I think that you have two choices.

1. Simple method.
https://github.com/ucbrise/clipper/issues/575#issuecomment-423011047

2. Create a custom model container.
http://clipper.ai/tutorials/custom_model_container/

**Comment by rkooo567** [comment]
Hi, @tosolveit. 

For the pre/postprocessing, you need to have a separate server that performs them before you query them. I believe we don't support pre/postprocessing between the query frontend and deployed models. 

Also, as @withsmilo mentioned, Clipper does not currently support json format input for queries. Other than the way mentioned above in #575 , you can also send serialized json bytes and deserialize in your prediction function. (We understand it can be a bad design since the prediction function should know how to process the input.) @simon-mo mentioned we can probably support more robust input type in the future pipelines (like json as you mentioned). 

Lastly, in the future release, the preprocessing function itself can be deployed as a model. And you can get the output of pre-processing model and feed it into the prediction model. This is an example of prediction pipelines. We are currently implementing something like this to let you compose models together in the next version Clipper, stay tuned!
