### ISSUE TITLE
Does clipper support other client protocol like GraphQL?

### ISSUE THREAD

**Issue by xunzhang** [ucbrise/clipper#641]
Does clipper support other kinds of client protocol except REST? For example, I'd like to add some logic inside clipper to dispatch requests from client side so GraphQL is more flexible. If not, is that easy to extent to other protocol such as GraphQL or rpc? Thanks.

**Comment by rkooo567** [comment]
As far as I know, no. Please correct me if there's a clear way to do so @simon-mo. Model servings are happening through Query Frontend written in C++, so if you want to use GraphQL/RPC, you can modify it to support other protocols. Check https://github.com/ucbrise/clipper/tree/develop/src/frontends.  

Another way I can think of is to add another layer that communicates with Query frontend and has an interface for GraphQL. I am not sure if it is a good idea because the strength of Clipper is its latency (more layers can increase latency).
