### ISSUE TITLE
Retraining on airflow?

### ISSUE THREAD

**Issue by itobysq** [ucbrise/clipper#668]
Great work so far, I really like the flexibility of the platform.

How do you recommend doing scheduled retraining? I typically train models with apache airflow. If I use clipper, I run into a problem because I am running a container inside of a container.

**Comment by rkooo567** [comment]
Hi, @itobysq. Could you elaborate a little more about ` I run into a problem because I am running a container inside of a container`? I suppose your airflow server is a container and when you try to run a clipper inside, it causes a problem? Am I correct?

**Comment by itobysq** [comment]
Thank you for the swift reply. Yes, that's what's happening. I am not reporting a problem. I just want to know what is the most common way to schedule retraining and deploying a model with Clipper. Before Clipper I just build pickle files on an airflow scheduler. I would like to take advantage of Clipper's ability to revert and all of its other great features.

**Comment by rkooo567** [comment]
Are you using KuberentesConatinerManager or DockerContainerManager for your cluster?

**Comment by rkooo567** [comment]
Sorry my comment was vague. If you use Kubernentes, the typical scenario is like this. Details might vary. 

1. Clipper has a `KuberentesManager` class that is used as a parameter of ClipperConnection. There was one setup guide about 5 months ago. Here is the link. https://github.com/ucbrise/clipper/issues/598. 

2. Once you somehow setup Clipper in your Kuberentes cluster, you can just easily use `deployers` in your Airflow server once retraining is done. It will wrap the model to the default RPC server image, push the image to the registry you specified, and deploy on Clipper. You can read `deployers` code if you want more detail. There is also an API doc http://docs.clipper.ai/en/v0.3.0/model_deployers.html.

3. For container in the container situation, you just simply need to use Docker inside Airflow container. `ClipperConnection` can find a clipper instances inside Kuberentes. I believe if you use `deployer`, it will be automatically handle. Also, here is @simon-mo's quote. 

you can train your model in docker container, and use docker in docker to push the trained model to clipper with new version number. 

So the typical scenario can be 
1. Setup Clipper inside Kuberentes cluster. 
2. get a connection to Clipper using `ClipperConnection(KubernetesContainerManager(somethingsomething).connect()`
3. Use `deployer` with the correct version number instead of pickling your models after retraining. It will deploy the retrained model on Clipper as well as pushing the model image on the top of its default image. You can also customize the model image if our default image is not sufficient for your purpose. Here is the link. http://clipper.ai/tutorials/custom_model_container/

@withsmilo @simon-mo  Please add more comments if my answer is not sufficient!

**Comment by itobysq** [comment]
Thank you for the thorough answer, I really appreciate it. I hope to try your suggestion later in the coming week.

**Comment by rkooo567** [comment]
Sounds good! @itobysq. Let us know if there will be any issues!

**Comment by withsmilo** [comment]
Hi, @itobysq. 
I think that the 'scheduled retraining' you mentioned above depends on how much automation your project requires on the ML pipeline system. This is a discussion of system architecture, which goes beyond the scope of Clipper, but here are some examples of how the system is configured using Clipper.
1. Wehkamp
https://medium.com/wehkamp-techblog/the-wehkamp-ml-platform-eb46638dd8d2

2. Our team constructed the Automated ML pipeline system as shown below.
    * Airflow: overall workflow management
    * ModelCreator: model training + automated model selection
    * ModelDeployer: model deployment using clipper_admin
    * kubernetes cluster : model serving using Clipper

@rkooo567 . Your guide is very useful! Great!
