### ISSUE TITLE
What you need to Modify the current develop version to get ensemble results

### ISSUE THREAD

**Issue by coldtomatojuice** [ucbrise/clipper#683]
Currently Clipper can only serve result from a single model that is linked to an application where a REST end point is set. however, most functions needed for serving results from multiple models are implemented in the code and I guess it is for the future revision that might enable clipper to select optimized models among all linked models according to a policy chosen. 

As per the issue #579 and others, there are some requirements to use multiple models linked to a single application, that is, an ensemble method. However, since it is only possible to get a single model result, at one REST request, to implement ensemble model, users must program their own method, and this was annoying.

Below is slight modifications of the code to let clipper to serve multiple model results at one REST request. To do that, 

it changes 
 - code that disables to run functions if there exists more thatn a model linked to an application
 - output return types of data
 - process multiple output result iteratively
 - post-process for multi model outputs

it uses the default policy, such that a single model result can still be served

it currently merges data from models and returns, but if you want ensembles of results,
you can implement your own ensemble methods in 'query_frontend.cpp'

below are what you need to fix in the Clipper
you can also check it from my fork : https://github.com/coldtomatojuice/clipper (Branch: ensemble)

[clipper_admin.py]
in the function 'def link_model_to_app(self, app_name, model_name)'
get argument 'model_name' as a string list (not a string)
so that, it can pass REST API a model name list

line:285
```
req_json = json.dumps({
            "app_name": app_name,
            "model_names": model_name
        })
```

[datatypes.cpp]
Change the output return type
Output output -> std::vector<Output> output

line:238
```
Response::Response(Query query, QueryId query_id, const long duration_micros,
                   std::vector<Output> output, const bool output_is_default,
                   const boost::optional<std::string> default_explanation)

```
[datatypes.hpp]
Change the output return type
Output output -> std::vector<Output> output

line:284
```
Response(Query query, QueryId query_id, const long duration_micros,
           std::vector<Output> output, const bool is_default,
           const boost::optional<std::string> default_explanation);

```
Change the output return type

line:300
`std::vector<Output> output_;
`
[query_processor.cpp]
Get a vector<Output> return from combine_predictions
Output -> vector<Output>

line:138
```
std::pair<vector<Output>, bool> final_output = current_policy->combine_predictions(
        selection_state, query, *outputs_ptr);

```
[selection_policies.hpp]
Modify a parameter for the 'combine_predictions'

line:67
```
virtual const std::pair<std::vector<Output>, bool> combine_predictions(
      const std::shared_ptr<SelectionState>& state, Query query,
      std::vector<Output> predictions) const = 0;

```
line:137
```
  const std::pair<std::vector<Output>, bool> combine_predictions(
      const std::shared_ptr<SelectionState>& state, Query query,
      std::vector<Output> predictions) const override;

```
[selection_policies.cpp]
Make below as a comment

line:75
```
//    if (num_candidate_models > 1) {
//      log_error_formatted(LOGGING_TAG_SELECTION_POLICY,
//                          "{} candidate models provided for query with label "
//                          "{}. Picking the first one.",
//                          num_candidate_models, query.label_);
//    }

```
Generate multiple objects

line:81
```
//    tasks.emplace_back(query.input_, query.candidate_models_.front(), 1.0,
//                       query_id, query.latency_budget_micros_);
    for(auto candidate_model : query.candidate_models_){
      tasks.emplace_back(query.input_, candidate_model, 1.0, query_id, query.latency_budget_micros_);
    }

```
Make below as a comment

line:101
```
//    log_error_formatted(LOGGING_TAG_SELECTION_POLICY,
//                        "DefaultOutputSelectionPolicy only expecting 1 "
//                        "output but found {}. Returning the first one.",
//                        predictions.size());

```
Make the return type as a vector

line:90
`const std::pair<std::vector<Output>, bool> DefaultOutputSelectionPolicy::combine_predictions(`

Modify original single output to a vector output

line:94
`    return std::make_pair(std::move(predictions), false);`
line:99
`    return std::make_pair(std::move(predictions), false);`

[query_front.hpp]
Push back models iteratively

line:693
`versioned_models.push_back(clipper::VersionedModelId(m, requested_version));`

Formatting output string. you can fix this part. 
line:490
```
//    std::string y_hat_str = parse_output_y_hat(query_response.output_.y_hat_);
    std::string y_hat_str ("");
    for(auto output_ele : query_response.output_){
      y_hat_str += parse_output_y_hat(output_ele.y_hat_);
    }
    y_hat_str += "]";
    y_hat_str = "[" + y_hat_str;

```
you can simply get ensembled results such as average, min, max, by using custom functions here.
however, I think it is more recommended to program policies to make such results, rather than just merging results

**Comment by withsmilo** [comment]
@coldtomatojuice , Great works! Could you please create a pull request that includes all your work?

**Comment by coldtomatojuice** [comment]
@withsmilo Sure, I will. Thanks!

**Comment by withsmilo** [comment]
@simon-mo : Does Clipper have any plan about `selection policy`?

**Comment by RehanSD** [comment]
@withsmilo @coldtomatojuice Clipper has worked on selection policies before; however, we decided not to implement native selection policies because they require containers to hold state. We have worked on creating a flask app that sits on top of Clipper for A/B, smoke and Blue Green testing.

**Comment by rkooo567** [comment]
I think we need some discussion about merging this into our `develop` right now. 

This is a naive way of supporting ensemble results, so instead of merging into `develop` directly, it might be better creating a new branch for this (for more features). Also, we should take care of some backward compatibility as well as unit tests. If the flask app works well, we probably don't need to have this feature on Query Frontend. 

We will get back to this around the end of May. And also thank you for the tips and PR @coldtomatojuice!

**Comment by coldtomatojuice** [comment]
Yes, I fully understand the plan what you guys have on upcoming clipper versions, so I issued this first to let people know the way they can modify clipper instantly to get ensemble results from multiple models. 
if there are more requirements regarding this feature, it would be better to develop some instant ensemble features, not to make conflict with flask apps, I reckon. 
Thank you for your comment! @rkooo567 @withsmilo

**Comment by withsmilo** [comment]
@RehanSD @rkooo567 @coldtomatojuice 
Thank you for your comments.

My opinion is that implementing some selection policies in Clipper can make the query_frontend a bottleneck in very high traffic environments and make error handling very difficult because the response times of ensemble models are various and may not have a uniform pattern. When using Clipper at the production level, I think bottlenecks should occur in the model service, not the query_frontend, and should scale-out the model service as much as possible.

So I agree to create a flask app that implements the selection policy in front of the Clipper. It will be very nice if the flask app could support both real-time and batch updates to the selection policy. I'm also designing a flask app that implements a variety of MAB algorithms, and I'll share it when it comes to performance.

@coldtomatojuice , I am really sorry that I could not give good news despite the great contribution.

**Comment by rkooo567** [comment]
@withsmilo @coldtomatojuice  I am planning to update our contribution doc in a few week. I will add this issue as a tip until our flask app is successfully merged.

**Comment by rkooo567** [comment]
@coldtomatojuice Thanks for the contribution again! I will add this link to the new contribution doc. Also, please feel free to contribute other features if you have!

**Comment by jeffjunzhang** [comment]
Hi @rkooo567, where can we find the "flask app"? Would it be possible to share it somewhere (even if it is on a very early stage) so that we can test on it? Thank you.

**Comment by asauray** [comment]
I believe adding a Flask app in front of Clipper is not a good idea. Python is a garbage collected language and using it as a proxy may result in expected latency, which goes against the goal of Clipper.

Could you explain why you think implementing the feature in query would make it a bottleneck @withsmilo ? I think the only problem here lies in the statefulness of Clipper Query. I believe this problem should be addressed separately.

Overall, I think that adding this feature in Query makes more sense.

**Comment by asauray** [comment]
Also, have you considered using Lua for implementing those policies ? @coldtomatojuice

**Comment by rkooo567** [comment]
@jeffjunzhang Currently, there's no progress in this because every contributors are busy. 
@antoinesauray That's correct. The reason why we thought about an additional layer is because query frontend is designed to stateless to be easily scaled (But we also found out query frontend has long-lived TCP connection with model containers, so it is technically not stateless now). Flask app was a hypothetical idea because it was the quickest way to develop prototype implementation. Our plan was to implement proof of concept using Flask, see the result, and implement with a different language if the result is not suitable for Clipper.
