### ISSUE TITLE
Question: why query-frontend occupies 1000m cpu for 0 requests?

### ISSUE THREAD

**Issue by liu-bote** [ucbrise/clipper#695]
I deployed a logistic regression model with Clipper on k8s, and I found that the query-frontend always occupies more than 1000m cpu even if there is no requests to it. Why is query-frontend so busy and what is it doing?

$kubectl top pod
query-frontend-0-xxxxxxxxx-xxxxx 1048m 42Mi

**Comment by simon-mo** [comment]
Hi thanks for the issue!

This is a bug we just fixed https://github.com/ucbrise/clipper/commit/db35528b6a670e16d9123d681898452060c9d816

We are roll out a new version in next two days. 

So if this is urgent you can install the development version of Clipper by
```
pip install git+https://github.com/ucbrise/clipper.git@develop#subdirectory=clipper_admin
```

Otherwise you can `pip install -U clipper_admin` when the bug fix come along.
