### ISSUE TITLE
Way to deploy model but have it not become the current version

### ISSUE THREAD

**Issue by rp4fx12** [ucbrise/clipper#698]
Hi, 

Is there a way to deploy a model but not have it be the current version of that model?

The specific use case I was thinking of is to deploy a new model, sanity test and then make it the current version after deployment. I guess I can deploy it, set the current version back to the previous version but I'm still not sure if there's a way to route the request to the new model version. Not sure if what I'm saying makes sense.

Thanks!

**Comment by withsmilo** [comment]
Hi, @rp4fx12 
The latest Clipper checks only the 'external' status of the model which is deployed by you as following.
* docker_container_manager : whether the status is healthy or not ([src](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/docker/docker_container_manager.py#L408-L415))
* kubernetes_container_manager : whether the number of running replicas is correct or not ([src](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py#L527-L537))

If you'd like to do some 'internal' sanity tests after deploying a new model, you have to create a custom model container. Please see, http://clipper.ai/tutorials/custom_model_container/. Perhaps you have to add your sanity test codes before starting the RPCService in python_closure_container.py. ([src](https://github.com/ucbrise/clipper/blob/develop/containers/python/python_closure_container.py#L61))

Finally, these steps are likely to proceed.
1. [Clipper] Start to deploy a new version of your model to your cluster.
2. [Cluster] Start a replica of the model.
3. [Container] Load the model file which was pickled already.
3. [Container] Do sanity test. (**<- your codes**)
4. [Container] If success, start the RPCService and finish the deployment.
5. [Container] If failed, exit with an error code. (**<- your codes**) Clipper will not switch to the new version because this container is exited.
